-- MySQL Script generated by MySQL Workbench
-- 02/24/15 16:06:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- USE `mydb` ;

-- -----------------------------------------------------
-- Table `Profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Profiles` (
  `profileId` INT NOT NULL,
  `language` VARCHAR(45) NULL,
  `displayName` VARCHAR(45) NULL,
  `bio` LONGTEXT NULL,
  `favoriteNum` INT NULL,
  `Accounts_accountId` INT NOT NULL,
  PRIMARY KEY (`profileId`),
  INDEX `fk_Profiles_Accounts1_idx` (`Accounts_accountId` ASC),
  UNIQUE INDEX `profileId_UNIQUE` (`profileId` ASC),
  CONSTRAINT `fk_Profiles_Accounts1`
    FOREIGN KEY (`Accounts_accountId`)
    REFERENCES `Accounts` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounts` (
  `accountId` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `registerDate` DATETIME NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `stateProvidence` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NOT NULL,
  `canStream` TINYINT(1) NOT NULL,
  `Profiles_profileId` INT NOT NULL,
  `streamKey` VARCHAR(256) NULL,
  PRIMARY KEY (`accountId`),
  INDEX `fk_Accounts_Profiles_idx` (`Profiles_profileId` ASC),
  UNIQUE INDEX `accountId_UNIQUE` (`accountId` ASC),
  CONSTRAINT `fk_Accounts_Profiles`
    FOREIGN KEY (`Profiles_profileId`)
    REFERENCES `Profiles` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Favorites` (
  `favId` INT NOT NULL,
  `Profiles_profileId` INT NOT NULL,
  `streamer` INT NULL,
  PRIMARY KEY (`favId`, `Profiles_profileId`),
  INDEX `fk_Favorites_Profiles1_idx` (`Profiles_profileId` ASC),
  UNIQUE INDEX `favId_UNIQUE` (`favId` ASC),
  CONSTRAINT `fk_Favorites_Profiles1`
    FOREIGN KEY (`Profiles_profileId`)
    REFERENCES `Profiles` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item` (
  `itemId` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `Profiles_profileId` INT NOT NULL,
  `itemType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`itemId`),
  UNIQUE INDEX `gameId_UNIQUE` (`itemId` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  INDEX `fk_Games_Profiles1_idx` (`Profiles_profileId` ASC),
  UNIQUE INDEX `itemType_UNIQUE` (`itemType` ASC),
  CONSTRAINT `fk_Games_Profiles1`
    FOREIGN KEY (`Profiles_profileId`)
    REFERENCES `Profiles` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
